---
title: "distance_analysis_QKweight_swaps (14m)"
date: "2025-03-24"
output:
  html_document:
    keep_md: yes
    toc: yes
    toc_float: yes
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(dpi = 300, fig.format = "png")
```

```{r include=FALSE}
library(tidyverse)
library(lmtest)
library(forcats)
library(broom)
library(lme4)
library(viridis)
library(ggridges)
library(lmerTest)
library(ggrepel)
library(RColorBrewer)

all_colors <- viridis::magma(10)
```


# Load original and baseline data

```{r}

# setwd("/Users/seantrott/Dropbox/UCSD/Research/Ambiguity/SSD/entangled_meanings/src/analysis/")

########## Intact Model
directory_path <- "../../data/processed/rawc/pythia/distances/"

csv_files <- list.files(path = directory_path, pattern = "*.csv", full.names = TRUE)
csv_list <- csv_files %>%
  map(~ read_csv(.))
df_intact_all <- bind_rows(csv_list) %>%
  mutate(Layer = Layer + 0)
df_intact <- df_intact_all %>%
  filter(mpath == "EleutherAI/pythia-14m")

table(df_intact$mpath)
table(df_intact$Layer)

########## Read in baselines
directory_path <- "../../data/processed/rawc/pythia/pythia-QKmod-random-heads/"

csv_files <- list.files(
  path = directory_path,
  pattern = "\\.csv$",  # safer than "*.csv"
  full.names = TRUE,
  recursive = TRUE      # <-- this enables recursion
)

csv_list <- csv_files %>%
  map(~ read_csv(.))
df_baselines <- bind_rows(csv_list) %>%
  mutate(Layer = Layer + 0) %>%
  mutate(heads_modified = case_when(
    heads_modified %in% c("[2, 3]", "[3, 2]") ~ "[2, 3]",
    TRUE ~ heads_modified
  ))

table(df_baselines$heads_modified)
table(df_baselines$model_modification)
table(df_baselines$Layer)

```


# Zero ablation analysis

## Load data

```{r}
# setwd("/Users/seantrott/Dropbox/UCSD/Research/Ambiguity/SSD/entangled_meanings/src/analysis/")
# setwd("/Users/pamelariviere/Desktop/projects/entangled_meanings/src/analysis/")

########## Read in swapped ones
directory_path <- "../../data/processed/rawc/pythia/pythia-QKmod/distances_ablate_zero//"

csv_files <- list.files(
  path = directory_path,
  pattern = "\\.csv$",  # safer than "*.csv"
  full.names = TRUE,
  recursive = TRUE      # <-- this enables recursion
)

csv_list <- csv_files %>%
  map(~ read_csv(.))
df_zero_ablations <- bind_rows(csv_list) %>%
  mutate(Layer = Layer + 0) #adjust for python zero-indexing

table(df_zero_ablations$heads_modified)
table(df_zero_ablations$Layer)


```



## Layerwise R2 by step

**TODO**: Tag all baselines as "Baseline"; compare distribution of R2 differences for baselines to each target head at each timestep. 

```{r r2_zero_ablations}

# Intact Model Layerwise R2 Curves Over Training Step
df_intact_R2 = df_intact %>% 
  filter(Layer > 0) %>% 
  group_by(mpath, revision, step, Layer, n_params) %>%
  summarise(r_intact = cor(Distance, mean_relatedness, method = "pearson"),
            r2_intact = r_intact ** 2)

# Baselines
df_baselines_ablatezero_R2 = df_baselines %>%
  filter(model_modification == "ablate_zero") %>%
  filter(Layer > 0) %>%
  group_by(mpath, revision, step, Layer, n_params, 
           model_modification, layers_modified, heads_modified) %>%
  summarise(r = cor(Distance, mean_relatedness, method = "pearson"),
            r2 = r ** 2) %>%
  mutate(condition = "Baseline")


# Swap Type: Zero
df_zero_ablations_R2 = df_zero_ablations %>%
  filter(Layer > 0) %>%
  group_by(mpath, revision, step, Layer, n_params, 
           model_modification, layers_modified, heads_modified) %>%
  summarise(r = cor(Distance, mean_relatedness, method = "pearson"),
            r2 = r ** 2) %>%
  mutate(condition = "Target")


#### Merge with intact
df_merged_all_zero_ablations = df_zero_ablations_R2 %>%
  ### Bind with baseline
  bind_rows(df_baselines_ablatezero_R2) %>%
  #### 
  full_join(df_intact_R2, by = c("step", 
                                  "Layer",
                                  "revision",
                                  "mpath",
                                  "n_params")) 
  


### Calculate differences
df_merged_all_zero_ablations = df_merged_all_zero_ablations %>%
  drop_na(r2) %>%
  mutate(r2_diff = r2_intact - r2,
         r2_frac = r2 / r2_intact) %>%
  mutate(step_mod = step + 1)
 

### Plot r2 diffs
df_merged_all_zero_ablations %>%
  ggplot(aes(x = step_mod, 
             y = r2_diff, 
             color = heads_modified)) +
  geom_vline(xintercept = 1000, linetype = "dashed", size = 1.2) +
  geom_hline(yintercept = 0, linetype = "dashed", size = 1.2) +
  geom_line(linewidth = 1.5) +  # or geom_point(), depending on the type of plot you want
  #geom_point(alpha = 0.7,size = 2) +
  facet_wrap(~ Layer) +  # Faceting by the 'Layer' variable
  scale_x_log10() + 
  scale_color_manual(values = viridisLite::viridis(6, option = "mako", begin = 0.8, end = 0.15)) +
  labs(title = "R2 Differences by Layer",
       x = "Timestep",
       y = "R2 Differences",
       color = "Modified Heads") +
  theme_minimal()

df_merged_all_zero_ablations %>%
  ggplot(aes(x = step_mod, 
             y = r2, 
             color = heads_modified)) +
  geom_vline(xintercept = 1000, linetype = "dashed", size = 1.2) +
  geom_hline(yintercept = 0, linetype = "dashed", size = 1.2) +
  geom_line(linewidth = 1.5) +  # or geom_point(), depending on the type of plot you want
  #geom_point(alpha = 0.7,size = 2) +
  facet_wrap(~ Layer) +  # Faceting by the 'Layer' variable
  scale_x_log10() + 
  scale_color_manual(values = viridisLite::viridis(6, option = "mako", begin = 0.8, end = 0.15)) +
  labs(title = "R2 by Layer",
       x = "Timestep",
       y = "R2",
       color = "Modified Heads") +
  theme_minimal()


df_merged_all_zero_ablations %>%
  group_by(condition, step_mod, Layer) %>%
  summarise(
    mean_r2_diff = mean(r2_diff, na.rm = TRUE),
    se_r2_diff = sd(r2_diff, na.rm = TRUE) / sqrt(n()),
    count = n()
  ) %>%
  ggplot(aes(x = step_mod, 
             y = mean_r2_diff, 
             color = condition, 
             fill = condition)) +
  geom_vline(xintercept = 1000, linetype = "dashed", size = 1.2) +
  geom_hline(yintercept = 0, linetype = "dashed", size = 1.2) +
  geom_ribbon(aes(ymin = mean_r2_diff - se_r2_diff,
                  ymax = mean_r2_diff + se_r2_diff),
              alpha = 0.2, color = NA) +
  geom_line(linewidth = 1.5) +
  scale_x_log10() + 
  scale_color_manual(values = viridisLite::viridis(4, option = "mako", begin = 0.8, end = 0.15)) +
  scale_fill_manual(values = viridisLite::viridis(4, option = "mako", begin = 0.8, end = 0.15)) +
  labs(title = "R2 Differences by Layer",
       x = "Timestep",
       y = "R2 Differences",
       color = "Condition",
       fill = "Condition") +
  theme_minimal() +
  facet_wrap(~Layer)

df_merged_all_zero_ablations %>%
  group_by(condition, step_mod, Layer) %>%
  summarise(
    mean_r2_frac = mean(r2_frac, na.rm = TRUE),
    se_r2_frac = sd(r2_frac, na.rm = TRUE) / sqrt(n()),
    count = n()
  ) %>%
  ggplot(aes(x = step_mod, 
             y = mean_r2_frac, 
             color = condition, 
             fill = condition)) +
  geom_vline(xintercept = 1000, linetype = "dashed", size = 1.2) +
  geom_hline(yintercept = 1, linetype = "dashed", size = 1.2) +
  geom_ribbon(aes(ymin = mean_r2_frac - se_r2_frac,
                  ymax = mean_r2_frac + se_r2_frac),
              alpha = 0.2, color = NA) +
  geom_line(linewidth = 1.5) +
  scale_x_log10() + 
  scale_color_manual(values = viridisLite::viridis(4, option = "mako", begin = 0.8, end = 0.15)) +
  scale_fill_manual(values = viridisLite::viridis(4, option = "mako", begin = 0.8, end = 0.15)) +
  labs(title = "% Intact R2",
       x = "Timestep",
       y = "% Intact R2",
       color = "Condition",
       fill = "Condition") +
  theme_minimal() +
  facet_wrap(~Layer)



df_merged_all_zero_ablations %>%
  group_by(condition, step_mod, Layer) %>%
  summarise(
    mean_r2 = mean(r2, na.rm = TRUE),
    se_r2 = sd(r2, na.rm = TRUE) / sqrt(n()),
    count = n()
  ) %>%
  ggplot(aes(x = step_mod, 
             y = mean_r2, 
             color = condition, 
             fill = condition)) +
  geom_vline(xintercept = 1000, linetype = "dashed", size = 1.2) +
  geom_hline(yintercept = 0, linetype = "dashed", size = 1.2) +
  geom_ribbon(aes(ymin = mean_r2 - se_r2,
                  ymax = mean_r2 + se_r2),
              alpha = 0.2, color = NA) +
  geom_line(linewidth = 1.5) +
  scale_x_log10() + 
  scale_color_manual(values = viridisLite::viridis(4, option = "mako", begin = 0.8, end = 0.15)) +
  scale_fill_manual(values = viridisLite::viridis(4, option = "mako", begin = 0.8, end = 0.15)) +
  labs(title = "R2 by Layer",
       x = "Timestep",
       y = "R2",
       color = "Condition",
       fill = "Condition") +
  theme_minimal() +
  facet_wrap(~Layer)


### collapsing across all layers
df_merged_all_zero_ablations %>%
  filter(Layer > 2) %>%
  group_by(condition, heads_modified, step_mod) %>%
  slice_max(r2, n = 1) %>%
  group_by(condition, step_mod) %>%
  summarise(
    mean_r2_diff = mean(r2_diff, na.rm = TRUE),
    se_r2_diff = sd(r2_diff, na.rm = TRUE) / sqrt(n()),
    count = n()
  ) %>%
  ggplot(aes(x = step_mod, 
             y = mean_r2_diff, 
             color = condition, 
             fill = condition)) +
  geom_vline(xintercept = 1000, linetype = "dashed", size = 1.2) +
  geom_hline(yintercept = 0, linetype = "dashed", size = 1.2) +
  geom_ribbon(aes(ymin = mean_r2_diff - se_r2_diff,
                  ymax = mean_r2_diff + se_r2_diff),
              alpha = 0.2, color = NA) +
  geom_line(linewidth = 1.5) +
  scale_x_log10() + 
  scale_color_manual(values = viridisLite::viridis(4, option = "mako", begin = 0.8, end = 0.15)) +
  scale_fill_manual(values = viridisLite::viridis(4, option = "mako", begin = 0.8, end = 0.15)) +
  labs(title = "R2 Differences Overall",
       x = "Timestep",
       y = "R2 Differences",
       color = "Condition",
       fill = "Condition") +
  theme_minimal()

### collapsing across all layers
df_merged_all_zero_ablations %>%
  filter(Layer > 2) %>%
  group_by(condition, heads_modified, step_mod) %>%
  slice_max(r2, n = 1) %>%
  group_by(condition, step_mod) %>%
  summarise(
    mean_r2_frac = mean(r2_frac, na.rm = TRUE),
    se_r2_frac = sd(r2_frac, na.rm = TRUE) / sqrt(n()),
    count = n()
  ) %>%
  ggplot(aes(x = step_mod, 
             y = mean_r2_frac, 
             color = condition, 
             fill = condition)) +
  geom_vline(xintercept = 1000, linetype = "dashed", size = 1.2) +
  geom_hline(yintercept = 1, linetype = "dashed", size = 1.2) +
  geom_ribbon(aes(ymin = mean_r2_frac - se_r2_frac,
                  ymax = mean_r2_frac + se_r2_frac),
              alpha = 0.2, color = NA) +
  geom_line(linewidth = 1.5) +
  scale_x_log10() + 
  scale_color_manual(values = viridisLite::viridis(4, option = "mako", begin = 0.8, end = 0.15)) +
  scale_fill_manual(values = viridisLite::viridis(4, option = "mako", begin = 0.8, end = 0.15)) +
  labs(title = "% Intact R2 Overall",
       x = "Timestep",
       y = "% Intact R2",
       color = "Condition",
       fill = "Condition") +
  theme_minimal()



########## Difference model
df_summ = df_merged_all_zero_ablations %>%
  filter(Layer > 2) %>%
  group_by(condition, heads_modified, step_mod) %>%
  slice_max(r2, n = 1) %>%
  group_by(condition, step_mod) %>%
  summarise(
    mean_r2_diff = mean(r2_diff, na.rm = TRUE),
    se_r2_diff = sd(r2_diff, na.rm = TRUE) / sqrt(n()),
    count = n()
  )

summary(df_summ$mean_r2_diff)
sd(df_summ$mean_r2_diff)
### Model
mod_r2_diff = lm(data = df_summ, mean_r2_diff ~ log10(step_mod) + condition)
summary(mod_r2_diff)
mod_r2_diff = lm(data = df_summ, mean_r2_diff ~ step_mod + condition)
summary(mod_r2_diff)


########## Percentage model
df_summ = df_merged_all_zero_ablations %>%
  filter(Layer > 2) %>%
  group_by(condition, heads_modified, step_mod) %>%
  slice_max(r2, n = 1) %>%
  group_by(condition, step_mod) %>%
  summarise(mean_r2_frac = mean(r2_frac, na.rm = TRUE))

summary(df_summ$mean_r2_frac)
sd(df_summ$mean_r2_frac)
### Model
mod_r2_frac = lm(data = df_summ, mean_r2_frac ~ log10(step_mod) + condition)
summary(mod_r2_frac)
mod_r2_frac = lm(data = df_summ, mean_r2_frac ~ step_mod + condition)
summary(mod_r2_frac)




df_merged_all_zero_ablations %>%
  group_by(condition) %>%
  summarise(m_frac = mean(r2_frac),
            sd_frac = sd(r2_frac),
            m_diff = mean(r2_diff),
            sd_diff = sd(r2_diff),
            min_frac = min(r2_frac),
            max_diff = max(r2_diff))

```

# Copy-step1 ablation analysis

## Load data

```{r}
# setwd("/Users/seantrott/Dropbox/UCSD/Research/Ambiguity/SSD/entangled_meanings/src/analysis/")
# setwd("/Users/pamelariviere/Desktop/projects/entangled_meanings/src/analysis/")

########## Read in swapped ones
directory_path <- "../../data/processed/rawc/pythia/pythia-QKmod/distances_ablate_copy_step1/"

csv_files <- list.files(
  path = directory_path,
  pattern = "\\.csv$",  # safer than "*.csv"
  full.names = TRUE,
  recursive = TRUE      # <-- this enables recursion
)

csv_list <- csv_files %>%
  map(~ read_csv(.))
df_copy_ablations <- bind_rows(csv_list) %>%
  mutate(Layer = Layer + 0) #adjust for python zero-indexing

table(df_copy_ablations$heads_modified)
table(df_copy_ablations$Layer)





```

## Layerwise R2 by step

```{r r2_copystep1_ablations}

# Intact Model Layerwise R2 Curves Over Training Step
df_intact_R2 = df_intact %>% 
  filter(Layer > 0) %>% 
  group_by(mpath, revision, step, Layer, n_params) %>%
  summarise(r_intact = cor(Distance, mean_relatedness, method = "pearson"),
            r2_intact = r_intact ** 2)

# Baselines
df_baselines_ablatecopy_R2 = df_baselines %>%
  filter(model_modification == "ablate_copy_step1") %>%
  filter(Layer > 0) %>%
  group_by(mpath, revision, step, Layer, n_params, 
           model_modification, layers_modified, heads_modified) %>%
  summarise(r = cor(Distance, mean_relatedness, method = "pearson"),
            r2 = r ** 2) %>%
  mutate(condition = "Baseline")


# Swap Type: Zero
df_copy_ablations_R2 = df_copy_ablations %>%
  filter(Layer > 0) %>%
  group_by(mpath, revision, step, Layer, n_params, 
           model_modification, layers_modified, heads_modified) %>%
  summarise(r = cor(Distance, mean_relatedness, method = "pearson"),
            r2 = r ** 2) %>%
  mutate(condition = "Target")


#### Merge with intact
df_merged_all_copy_ablations = df_copy_ablations_R2 %>%
  ### Bind with baseline
  bind_rows(df_baselines_ablatecopy_R2) %>%
  full_join(df_intact_R2, by = c("step", 
                                  "Layer",
                                  "revision",
                                  "mpath",
                                  "n_params"))


### Calculate differences
df_merged_all_copy_ablations = df_merged_all_copy_ablations %>%
  drop_na(r2) %>%
  mutate(r2_diff = r2_intact - r2,
         r2_frac = r2 / r2_intact) %>%
  mutate(step_mod = step + 1)
 

df_merged_all_copy_ablations %>%
  ggplot(aes(x = step_mod, 
             y = r2_diff, 
             color = heads_modified)) +
  geom_vline(xintercept = 1000, linetype = "dashed", size = 1.2) +
  geom_hline(yintercept = 0, linetype = "dashed", size = 1.2) +
  geom_line(linewidth = 1.5) +  # or geom_point(), depending on the type of plot you want
  #geom_point(alpha = 0.7,size = 2) +
  facet_wrap(~ Layer) +  # Faceting by the 'Layer' variable
  scale_x_log10() + 
  scale_color_manual(values = viridisLite::viridis(6, option = "mako", begin = 0.8, end = 0.15)) +
  labs(title = "R2 Differences by Layer",
       x = "Timestep",
       y = "R2 Differences",
       color = "Modified Heads") +
  theme_minimal()

df_merged_all_copy_ablations %>%
  ggplot(aes(x = step_mod, 
             y = r2_frac, 
             color = heads_modified)) +
  geom_vline(xintercept = 1000, linetype = "dashed", size = 1.2) +
  geom_hline(yintercept = 1, linetype = "dashed", size = 1.2) +
  geom_line(linewidth = 1.5) +  # or geom_point(), depending on the type of plot you want
  #geom_point(alpha = 0.7,size = 2) +
  facet_wrap(~ Layer) +  # Faceting by the 'Layer' variable
  scale_x_log10() + 
  scale_color_manual(values = viridisLite::viridis(6, option = "mako", begin = 0.8, end = 0.15)) +
  labs(title = "% Intact R2 by Layer",
       x = "Timestep",
       y = "% Intact R2",
       color = "Modified Heads") +
  theme_minimal()

df_merged_all_copy_ablations %>%
  ggplot(aes(x = step_mod, 
             y = r2, 
             color = heads_modified)) +
  geom_vline(xintercept = 1000, linetype = "dashed", size = 1.2) +
  geom_hline(yintercept = 0, linetype = "dashed", size = 1.2) +
  geom_line(linewidth = 1.5) +  # or geom_point(), depending on the type of plot you want
  #geom_point(alpha = 0.7,size = 2) +
  facet_wrap(~ Layer) +  # Faceting by the 'Layer' variable
  scale_x_log10() + 
  scale_color_manual(values = viridisLite::viridis(6, option = "mako", begin = 0.8, end = 0.15)) +
  labs(title = "R2 by Layer",
       x = "Timestep",
       y = "R2",
       color = "Modified Heads") +
  theme_minimal()


### collapsing across all layers
df_merged_all_copy_ablations %>%
  filter(Layer > 2) %>%
  group_by(condition, heads_modified, step_mod) %>%
  slice_max(r2, n = 1) %>%
  group_by(condition, step_mod) %>%
  summarise(
    mean_r2_diff = mean(r2_diff, na.rm = TRUE),
    se_r2_diff = sd(r2_diff, na.rm = TRUE) / sqrt(n()),
    count = n()
  ) %>%
  ggplot(aes(x = step_mod, 
             y = mean_r2_diff, 
             color = condition, 
             fill = condition)) +
  geom_vline(xintercept = 1000, linetype = "dashed", size = 1.2) +
  geom_hline(yintercept = 0, linetype = "dashed", size = 1.2) +
  geom_ribbon(aes(ymin = mean_r2_diff - se_r2_diff,
                  ymax = mean_r2_diff + se_r2_diff),
              alpha = 0.2, color = NA) +
  geom_line(linewidth = 1.5) +
  scale_x_log10() + 
  scale_color_manual(values = viridisLite::viridis(4, option = "mako", begin = 0.8, end = 0.15)) +
  scale_fill_manual(values = viridisLite::viridis(4, option = "mako", begin = 0.8, end = 0.15)) +
  labs(title = "R2 Differences Overall",
       x = "Timestep",
       y = "R2 Differences",
       color = "Condition",
       fill = "Condition") +
  theme_minimal()

### collapsing across all layers
df_merged_all_copy_ablations %>%
  filter(Layer > 2) %>%
  group_by(condition, heads_modified, step_mod) %>%
  slice_max(r2, n = 1) %>%
  group_by(condition, step_mod) %>%
  summarise(
    mean_r2_frac = mean(r2_frac, na.rm = TRUE),
    se_r2_frac = sd(r2_frac, na.rm = TRUE) / sqrt(n()),
    count = n()
  ) %>%
  ggplot(aes(x = step_mod, 
             y = mean_r2_frac, 
             color = condition, 
             fill = condition)) +
  geom_vline(xintercept = 1000, linetype = "dashed", size = 1.2) +
  geom_hline(yintercept = 1, linetype = "dashed", size = 1.2) +
  geom_ribbon(aes(ymin = mean_r2_frac - se_r2_frac,
                  ymax = mean_r2_frac + se_r2_frac),
              alpha = 0.2, color = NA) +
  geom_line(linewidth = 1.5) +
  scale_x_log10() + 
  scale_color_manual(values = viridisLite::viridis(4, option = "mako", begin = 0.8, end = 0.15)) +
  scale_fill_manual(values = viridisLite::viridis(4, option = "mako", begin = 0.8, end = 0.15)) +
  labs(title = "% Intact R2 Overall",
       x = "Timestep",
       y = "% Intact R2",
       color = "Condition",
       fill = "Condition") +
  theme_minimal()




####### Difference model
df_summ = df_merged_all_copy_ablations %>%
  filter(Layer > 2) %>%
  group_by(condition, heads_modified, step_mod) %>%
  slice_max(r2, n = 1) %>%
  group_by(condition, step_mod) %>%
  summarise(
    mean_r2_diff = mean(r2_diff, na.rm = TRUE),
    se_r2_diff = sd(r2_diff, na.rm = TRUE) / sqrt(n()),
    count = n()
  )

summary(df_summ$mean_r2_diff)
sd(df_summ$mean_r2_diff)
### Model
mod_r2_diff = lm(data = df_summ, mean_r2_diff ~ log10(step_mod) + condition)
summary(mod_r2_diff)
mod_r2_diff = lm(data = df_summ, mean_r2_diff ~ step_mod + condition)
summary(mod_r2_diff)



####### Proportion model
df_summ = df_merged_all_copy_ablations %>%
  filter(Layer > 2) %>%
  group_by(condition, heads_modified, step_mod) %>%
  slice_max(r2, n = 1) %>%
  group_by(condition, step_mod) %>%
  summarise(
    mean_r2_frac = mean(r2_frac, na.rm = TRUE),
    se_r2_frac = sd(r2_frac, na.rm = TRUE) / sqrt(n()),
    count = n()
  )

summary(df_summ$mean_r2_frac)
sd(df_summ$mean_r2_frac)
### Model
mod_r2_frac = lm(data = df_summ, mean_r2_frac ~ log10(step_mod) + condition)
summary(mod_r2_frac)
mod_r2_frac = lm(data = df_summ, mean_r2_frac ~ step_mod + condition)
summary(mod_r2_frac)


df_merged_all_zero_ablations %>%
  group_by(condition) %>%
  summarise(m_frac = mean(r2_frac),
            sd_frac = sd(r2_frac),
            m_diff = mean(r2_diff),
            sd_diff = sd(r2_diff),
            min_frac = min(r2_frac),
            max_diff = max(r2_diff))

```
