---
title: "distance_analysis_QKweight_swaps"
output: html_document
date: "2025-03-24"
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(dpi = 300, fig.format = "pdf")
```

```{r include=FALSE}
library(tidyverse)
library(lmtest)
library(forcats)
library(broom)
library(lme4)
library(viridis)
library(ggridges)
library(lmerTest)
library(ggrepel)
library(RColorBrewer)

all_colors <- viridis::magma(10)
```

# Zero ablation analysis

## Load data

```{r}
# setwd("/Users/seantrott/Dropbox/UCSD/Research/Ambiguity/SSD/entangled_meanings/src/analysis/")
# setwd("/Users/pamelariviere/Desktop/projects/entangled_meanings/src/analysis/")

########## Intact Model
directory_path <- "../../data/processed/rawc/pythia/distances/"

csv_files <- list.files(path = directory_path, pattern = "*.csv", full.names = TRUE)
csv_list <- csv_files %>%
  map(~ read_csv(.))
df_intact_all <- bind_rows(csv_list) %>%
  mutate(Layer = Layer + 0)
df_intact <- df_intact_all %>%
  filter(mpath == "EleutherAI/pythia-14m")

table(df_intact$mpath)
table(df_intact$Layer)

########## Read in swapped ones
directory_path <- "../../data/processed/rawc/pythia/pythia-QKmod/distances_ablate_zero//"

csv_files <- list.files(
  path = directory_path,
  pattern = "\\.csv$",  # safer than "*.csv"
  full.names = TRUE,
  recursive = TRUE      # <-- this enables recursion
)

csv_list <- csv_files %>%
  map(~ read_csv(.))
df_zero_ablations <- bind_rows(csv_list) %>%
  mutate(Layer = Layer + 0) #adjust for python zero-indexing

table(df_zero_ablations$heads_modified)
table(df_zero_ablations$Layer)


```

## Layerwise R2 by step

```{r r2_zero_ablations}

# Intact Model Layerwise R2 Curves Over Training Step
df_intact_R2 = df_intact %>% 
  filter(Layer > 0) %>% 
  group_by(mpath, revision, step, Layer, n_params) %>%
  summarise(r_intact = cor(Distance, mean_relatedness, method = "pearson"),
            r2_intact = r_intact ** 2)


# Swap Type: Zero
df_zero_ablations_R2 = df_zero_ablations %>%
  filter(Layer > 0) %>%
  group_by(mpath, revision, step, Layer, n_params, 
           model_modification, layers_modified, heads_modified) %>%
  summarise(r = cor(Distance, mean_relatedness, method = "pearson"),
            r2 = r ** 2)


#### Merge with intact
df_merged_all_zero_ablations = df_zero_ablations_R2 %>%
  full_join(df_intact_R2, by = c("step", 
                                  "Layer",
                                  "revision",
                                  "mpath",
                                  "n_params"))


### Calculate differences
df_merged_all_zero_ablations = df_merged_all_zero_ablations %>%
  drop_na(r2) %>%
  mutate(r2_diff = r2_intact - r2) %>%
  mutate(step_mod = step + 1)
 

df_merged_all_zero_ablations %>%
  ggplot(aes(x = step_mod, 
             y = r2_diff, 
             color = heads_modified)) +
  geom_vline(xintercept = 1000, linetype = "dashed", size = 1.2) +
  geom_hline(yintercept = 0, linetype = "dashed", size = 1.2) +
  geom_line(linewidth = 1.5) +  # or geom_point(), depending on the type of plot you want
  #geom_point(alpha = 0.7,size = 2) +
  facet_wrap(~ Layer) +  # Faceting by the 'Layer' variable
  scale_x_log10() + 
  scale_color_manual(values = viridisLite::viridis(3, option = "mako", begin = 0.8, end = 0.15)) +
  labs(title = "R2 Differences by Layer",
       x = "Timestep",
       y = "R2 Differences",
       color = "Modified Heads") +
  theme_minimal()

df_merged_all_zero_ablations %>%
  ggplot(aes(x = step_mod, 
             y = r2, 
             color = heads_modified)) +
  geom_vline(xintercept = 1000, linetype = "dashed", size = 1.2) +
  geom_hline(yintercept = 0, linetype = "dashed", size = 1.2) +
  geom_line(linewidth = 1.5) +  # or geom_point(), depending on the type of plot you want
  #geom_point(alpha = 0.7,size = 2) +
  facet_wrap(~ Layer) +  # Faceting by the 'Layer' variable
  scale_x_log10() + 
  scale_color_manual(values = viridisLite::viridis(3, option = "mako", begin = 0.8, end = 0.15)) +
  labs(title = "R2 by Layer",
       x = "Timestep",
       y = "R2",
       color = "Modified Heads") +
  theme_minimal()

```

# Copy-step1 ablation analysis

## Load data

```{r}
# setwd("/Users/seantrott/Dropbox/UCSD/Research/Ambiguity/SSD/entangled_meanings/src/analysis/")
# setwd("/Users/pamelariviere/Desktop/projects/entangled_meanings/src/analysis/")

########## Intact Model
directory_path <- "../../data/processed/rawc/pythia/distances/"

csv_files <- list.files(path = directory_path, pattern = "*.csv", full.names = TRUE)
csv_list <- csv_files %>%
  map(~ read_csv(.))
df_intact_all <- bind_rows(csv_list) %>%
  mutate(Layer = Layer + 0)
df_intact <- df_intact_all %>%
  filter(mpath == "EleutherAI/pythia-14m")

table(df_intact$mpath)
table(df_intact$Layer)

########## Read in swapped ones
directory_path <- "../../data/processed/rawc/pythia/pythia-QKmod/distances_copy_step1/"

csv_files <- list.files(
  path = directory_path,
  pattern = "\\.csv$",  # safer than "*.csv"
  full.names = TRUE,
  recursive = TRUE      # <-- this enables recursion
)

csv_list <- csv_files %>%
  map(~ read_csv(.))
df_copy_ablations <- bind_rows(csv_list) %>%
  mutate(Layer = Layer + 0) #adjust for python zero-indexing

table(df_copy_ablations$heads_modified)
table(df_copy_ablations$Layer)



```

## Layerwise R2 by step

```{r r2_copystep1_ablations}

# Intact Model Layerwise R2 Curves Over Training Step
df_intact_R2 = df_intact %>% 
  filter(Layer > 0) %>% 
  group_by(mpath, revision, step, Layer, n_params) %>%
  summarise(r_intact = cor(Distance, mean_relatedness, method = "pearson"),
            r2_intact = r_intact ** 2)

# Swap Type: Zero
df_copy_ablations_R2 = df_copy_ablations %>%
  filter(Layer > 0) %>%
  group_by(mpath, revision, step, Layer, n_params, 
           model_modification, layers_modified, heads_modified) %>%
  summarise(r = cor(Distance, mean_relatedness, method = "pearson"),
            r2 = r ** 2)


#### Merge with intact
df_merged_all_copy_ablations = df_copy_ablations_R2 %>%
  full_join(df_intact_R2, by = c("step", 
                                  "Layer",
                                  "revision",
                                  "mpath",
                                  "n_params"))


### Calculate differences
df_merged_all_copy_ablations = df_merged_all_copy_ablations %>%
  drop_na(r2) %>%
  mutate(r2_diff = r2_intact - r2) %>%
  mutate(step_mod = step + 1)
 

df_merged_all_copy_ablations %>%
  ggplot(aes(x = step_mod, 
             y = r2_diff, 
             color = heads_modified)) +
  geom_vline(xintercept = 1000, linetype = "dashed", size = 1.2) +
  geom_hline(yintercept = 0, linetype = "dashed", size = 1.2) +
  geom_line(linewidth = 1.5) +  # or geom_point(), depending on the type of plot you want
  #geom_point(alpha = 0.7,size = 2) +
  facet_wrap(~ Layer) +  # Faceting by the 'Layer' variable
  scale_x_log10() + 
  scale_color_manual(values = viridisLite::viridis(3, option = "mako", begin = 0.8, end = 0.15)) +
  labs(title = "R2 Differences by Layer",
       x = "Timestep",
       y = "R2 Differences",
       color = "Modified Heads") +
  theme_minimal()

df_merged_all_copy_ablations %>%
  ggplot(aes(x = step_mod, 
             y = r2, 
             color = heads_modified)) +
  geom_vline(xintercept = 1000, linetype = "dashed", size = 1.2) +
  geom_hline(yintercept = 0, linetype = "dashed", size = 1.2) +
  geom_line(linewidth = 1.5) +  # or geom_point(), depending on the type of plot you want
  #geom_point(alpha = 0.7,size = 2) +
  facet_wrap(~ Layer) +  # Faceting by the 'Layer' variable
  scale_x_log10() + 
  scale_color_manual(values = viridisLite::viridis(3, option = "mako", begin = 0.8, end = 0.15)) +
  labs(title = "R2 by Layer",
       x = "Timestep",
       y = "R2",
       color = "Modified Heads") +
  theme_minimal()
```

# Rescue analysis

## Load data

```{r}
# setwd("/Users/seantrott/Dropbox/UCSD/Research/Ambiguity/SSD/entangled_meanings/src/analysis/")
# setwd("/Users/pamelariviere/Desktop/projects/entangled_meanings/src/analysis/")

########## Intact Model
directory_path <- "../../data/processed/rawc/pythia/distances/"

csv_files <- list.files(path = directory_path, pattern = "*.csv", full.names = TRUE)
csv_list <- csv_files %>%
  map(~ read_csv(.))
df_intact_all <- bind_rows(csv_list) %>%
  mutate(Layer = Layer + 0)
df_intact <- df_intact_all %>%
  filter(mpath == "EleutherAI/pythia-14m")

table(df_intact$mpath)
table(df_intact$Layer)

########## Read in swapped ones
directory_path <- "../../data/processed/rawc/pythia/pythia-QKmod/distances_rescue/"

csv_files <- list.files(
  path = directory_path,
  pattern = "\\.csv$",  # safer than "*.csv"
  full.names = TRUE,
  recursive = TRUE      # <-- this enables recursion
)

csv_list <- csv_files %>%
  map(~ read_csv(.))
df_rescue <- bind_rows(csv_list) %>%
  mutate(Layer = Layer + 0) #adjust for python zero-indexing

table(df_rescue$heads_modified)
table(df_rescue$Layer)


```

## Layerwise R2 by step

```{r r2_rescue}

# Intact Model Layerwise R2 Curves Over Training Step
df_intact_R2 = df_intact %>% 
  filter(Layer > 0) %>% 
  group_by(mpath, revision, step, Layer, n_params) %>%
  summarise(r_intact = cor(Distance, mean_relatedness, method = "pearson"),
            r2_intact = r_intact ** 2)


df_rescue_R2 = df_rescue %>%
  filter(Layer > 0) %>%
  group_by(mpath, revision, step, Layer, n_params, 
           model_modification, layers_modified, heads_modified) %>%
  summarise(r = cor(Distance, mean_relatedness, method = "pearson"),
            r2 = r ** 2)


#### Merge with intact
df_merged_all_rescue = df_rescue_R2 %>%
  full_join(df_intact_R2, by = c("step", 
                                  "Layer",
                                  "revision",
                                  "mpath",
                                  "n_params"))



### Calculate differences
df_merged_all_rescue = df_merged_all_rescue %>%
  drop_na(r2) %>%
  mutate(r2_diff = r2_intact - r2) %>%
  mutate(step_mod = step + 1)
 

df_merged_all_rescue %>%
  ggplot(aes(x = step_mod, 
             y = r2_diff, 
             color = heads_modified)) +
  geom_vline(xintercept = 1000, linetype = "dashed", size = 1.2) +
  geom_hline(yintercept = 0, linetype = "dashed", size = 1.2) +
  geom_line(linewidth = 1.5) +  # or geom_point(), depending on the type of plot you want
  #geom_point(alpha = 0.7,size = 2) +
  facet_wrap(~ Layer) +  # Faceting by the 'Layer' variable
  scale_x_log10() + 
  scale_color_manual(values = viridisLite::viridis(3, option = "mako", begin = 0.8, end = 0.15)) +
  labs(title = "R2 Differences by Layer",
       x = "Timestep",
       y = "R2 Differences",
       color = "Modified Heads") +
  theme_minimal()




#### REDO THIS: too many observations for r2_intact b/c it's for each "version" of mods

df_merged_all_rescue %>%
  select(-r, -r2_diff) %>%
  pivot_longer(cols = c(r2, r2_intact),
               values_to = "R2") %>%
  mutate(version = case_when(
    name == "r2_intact" ~ "Original",
    name == "r2" ~ heads_modified
  )) %>%
  distinct() %>%
  ggplot(aes(x = step_mod, y = R2, color = version)) +
  geom_vline(xintercept = 1000, linetype = "dashed", size = 1.2) +
  geom_line() +  # or geom_point(), depending on the type of plot you want
  facet_wrap(~ Layer) +  # Faceting by the 'Layer' variable
  scale_x_log10() + 
  scale_color_manual(values = viridisLite::viridis(4, option = "mako", begin = 0.8, end = 0.15)) +
  labs(title = "Raw R2 by Layer",
       x = "Timestep",
       y = "R2") +
  theme_minimal()
  


```
